VectorInstitute/FL4Health

examples/fedper_example/README.md, examples/fedper_example/client.py, examples/fedper_example/config.yaml, examples/fedper_example/server.py, examples/fenda_example/client.py, examples/models/fedper_cnn.py, fl4health/clients/apfl_client.py, fl4health/clients/basic_client.py, fl4health/clients/evaluate_client.py, fl4health/clients/fed_prox_client.py, fl4health/clients/fenda_client.py, fl4health/clients/moon_client.py, fl4health/clients/scaffold_client.py, fl4health/model_bases/apfl_base.py, fl4health/model_bases/fedper_base.py, fl4health/model_bases/fenda_base.py, fl4health/model_bases/moon_base.py, fl4health/model_bases/partial_layer_exchange_model.py, fl4health/server/tabular_feature_alignment_server.py, research/flamby/fed_ixi/fenda/client.py, research/flamby/fed_ixi/moon/moon_model.py, tests/clients/test_fed_prox_client.py, tests/clients/test_fenda_client.py, tests/clients/test_moon_client.py, tests/models/test_apfl_base.py, tests/models/test_fedper_base.py, tests/models/test_fenda_base.py
**Feature**
Clickup Ticket: https://app.clickup.com/t/8686ckn31
This PR adds in the FedPer method into the repository. The addition is fairly straightforward within our infrastructure. It's essentially just a globally trained feature extractor with a locally trained classification head in each client. I added an example using the infrastructure while also training it with MOON. So the example client **inherits** from the MOON client to apply the auxiliary losses to the model along with local personalization, which I thought was nice.
In the course of adding the method, I noticed a few small bugs in MOON and the auxiliary losses (like PerFCL) in the FENDA approaches. These have been fixed and tests have been added to ensure that they are indeed fixed.
Added losses associated with MOON's …
=> FedPer Implementation

tests/smoke_tests/run_smoke_test.py
Other
Clickup Ticket(s): https://app.clickup.com/t/8686njmnm
Refactoring the `_wait_for_process_to_finish_and_retrieve_logs` function to read the logs line-by-line so it can return the logs when the process times out.
None
=> Smoke tests: display client logs on timeout

poetry.lock
Fix
A security fix for `gitpython` has been released which solves the error by `pip-audit` in the CI check below. Here, I'm upgrading `gitpython` to the latest version.
https://github.com/VectorInstitute/FL4Health/actions/runs/7478823421
NA
=> Upgrading gitpython to 3.1.41 to fix a security issue

poetry.lock
Fix
A security fix for `jinja2` has been released which solves the error by `pip-audit` in the CI check below. Here, I'm upgrading `jinja2` to the latest version.
https://github.com/VectorInstitute/FL4Health/actions/runs/7493390403
NA
=> Upgrading jinja2 to 3.1.3 to fix a security issue

.github/workflows/static_code_checks.yaml
Fix
One more vulnerability has been found for Pillow 9.5.0 (https://github.com/advisories/GHSA-3f63-hfp8-52jq), ignoring it in `pip-audit` since we can't upgrade it right now.
NA
=> Ignoring one more pillow 9.5.0 vulnerability

fl4health/utils/random.py, tests/models/test_pca.py
[Fix]
Relaxed the floating point number tolerance used in `test_pca.py`.
Updated `test_pca.py`
=> Relax Floating Point Number Tolerance for PCA test

tests/smoke_tests/run_smoke_test.py
Fix
Fixing smoke tests metric errors is a pain because they are displayed one by one. Changing it here to display all of them at once to avoid multiple iterations of fixing them.
NA
=> Displaying all the smoke tests metrics errors at once

.pre-commit-config.yaml
Fix
Flake8 is not able to run on pre-commit bot, so skipping it for now.
NA
=> Skip flake8 on pre-commit bot

.github/workflows/static_code_checks.yaml, poetry.lock
Fix
Currently there is a W and B vulnerability that exists in the latest version. So upgrading doesn't fix it. Ignoring it for now.
=> Ignoring W and B vulnerability for now

research/picai/preprocessing.py, tests/test_picai/test_case.py
Clickup Ticket(s): [Fix Picai Channel Ordering](https://app.clickup.com/t/8688u62qb)
The channel of the scans (t2w, adc, hbv) are being written with incorrect file names. The root of the cause was the write method of PicaiCase. The scan paths were being sorted when they should not. They are being passed with an assumed order. I also added to the documentation to make this more clear. 
- Test to ensure we reading and writing picai case correctly
=> Fix picai channel ordering

fl4health/losses/mkmmd_loss.py, tests/losses/test_mkmmd_loss.py
Other
This PR adds tests for the MK-MMD loss updates suggested in the target PR. The tests modify both the original MK-MMD tests associated with the linear approximation and adds tests to cover the full approximation calculations constructed in the update. 
I also did some structural refactors to sort of "split" the linear vs. full approximation processing where I thought it made sense. Let me know if you disagree with any of it.
See above.
=> Update MK-MMD Loss Suggestions and Tests

.github/workflows/static_code_checks.yaml, fl4health/server/base_server.py, fl4health/server/client_level_dp_fed_avg_server.py, fl4health/server/evaluate_server.py, fl4health/server/instance_level_dp_server.py, fl4health/server/polling.py, fl4health/server/scaffold_server.py, fl4health/server/tabular_feature_alignment_server.py, poetry.lock, pyproject.toml, research/picai/picai_server.py, tests/server/test_base_server.py, tests/smoke_tests/run_smoke_test.py, tests/test_utils/custom_client_proxy.py
[Feature | Fix | Documentation | **Other** ]
Clickup Ticket(s): [Upgrade Core Dependencies (flwr)](https://app.clickup.com/t/8688zkaey)
Short PR to upgrade Flower from 1.7 to 1.9. There was some small changes to the server including: 
- get_initial_parameters now takes an int as its first argument (server round)
- fit methods now return elapsed time along with history 
- the addition of the group_id parameter in evaluate clients which is set to server round when available following flwr
flwr also changed the logging format so I had to update the smoke tests. Lastly, in the upgrade to 1.9, flwr upgraded cryptography to a version that no longer fails pip audit so I removed the corresponding vulnerabilities from ignore.
NA
=> Update flwr 1.7 to 1.9

fl4health/clients/basic_client.py
Added a hook 'update_after_epoch'. Added this mainly to allow users to use lr_schedulers and call scheduler.step() in this method. The reason I created a hook rather than a self.lr_scheduler attribute is that the epoch argument for the pytorch step method is about to be deprecated. So we can leave it up to the user how the lr_scheduler step is called. Additionally this allows the user to add a log with the current LR as well. The log could have been added to the _handle_logging method, but for the nnunet lr_scheduler at least, they overrode the step function and don't update the self._last_lr attribute so the only way to get the LR would be to get it from the optimizer state_dict, but that felt messy. Hence my decision to just add a hook and …
=> added epoch hook

fl4health/clients/basic_client.py, fl4health/utils/typing.py, research/picai/fl_nnunet/config.yaml, research/picai/fl_nnunet/nnunet_client.py
- Added an update_before_epoch hook method to BasicClient
- Used update_before_epoch to enable lr scheduling in nnUNetClient
- Added the add_to_initial_log_str attribute to Basic Client to allow users to add information to the initial log string (such as current LR)
- Reformatted logging in _handle_logging method of BasicClient to make things more readable
Note: The add_to_initial_log_str seemed like the cleanest solution to me to allow users to add info to the inital log string. I made sure to add a comment in the BasicClient init where the attribute is defined to explain how it works. Although it is a functionality that could be easily overlooked if users don't look through the BasicClient code. 
Additionally, one thing i did notice is that …
=> Added epoch hook for lr scheduling and made client logs look better

poetry.lock, pyproject.toml
Seems like nltk version 3.8.2 no longer exists so rolling back the dependency to ^3.8.0
=> decreased nltk version from ^3.8.1 to ^3.8.0

fl4health/clients/apfl_client.py, fl4health/clients/basic_client.py, fl4health/clients/constrained_fenda_client.py, fl4health/clients/fed_prox_client.py, fl4health/clients/flash_client.py, fl4health/clients/moon_client.py, fl4health/clients/perfcl_client.py, fl4health/clients/scaffold_client.py, research/picai/fl_nnunet/config.yaml, research/picai/fl_nnunet/nnunet_client.py, research/picai/fl_nnunet/nnunet_utils.py, research/picai/fl_nnunet/start_client.py, research/picai/picai_client.py, tests/clients/test_constrained_fenda_client.py, tests/clients/test_moon_client.py, tests/clients/test_perfcl_client.py
1. Updated the nnunet client LR Scheduler
- Now updates every step
- Takes into account the total number of rounds when determining max step
2. Fixed an issue where RAM usage would steadily increase throughout training and cause OOM
- Not sure if this issue was specific to the nnunet client or affects all clients
- RAM usage would steadily increase after each round eventually leading to an OOM.
- Resolved issue by running garbage collection at the beginning of each round. Implemented this only for the nnunet client using a hook.
3. Added Gradient Clipping to nnunet client
- By default, nnunet 2.5.1 does gradient some gradient clipping during training
- Added this to the nnunet client so that we could be consistent
- In order to add this …
=> Changed nnunet LR Schedule and fixed memory leak

examples/README.MD, examples/fedsimclr_example/fedsimclr_finetuning_example/README.md
Documentation
Clickup Ticket(s): [Link(s) if applicable.](https://app.clickup.com/t/8689erm57)
Adding a README, along the lines specified in the ticket below, to the examples folder.
NA
=> Adding a README to the examples folder.

fl4health/clients/basic_client.py, fl4health/clients/nnunet_client.py, fl4health/server/base_server.py, fl4health/utils/nnunet_utils.py, research/picai/fedavg/client.py, research/picai/fedavg/server.py, tests/smoke_tests/load_from_checkpoint_example/client.py, tests/smoke_tests/load_from_checkpoint_example/server.py, tests/smoke_tests/run_smoke_test.py
Quick follow up of #234 addressing some of Davids smaller CRs.
=> Add updates for smaller CRs by David

fl4health/clients/nnunet_client.py, fl4health/utils/dataset.py, fl4health/utils/partitioners.py, fl4health/utils/sampler.py, tests/utils/partitioners_test.py
Feature
Clickup Ticket(s): [Link](https://app.clickup.com/t/8689qhwfz)
This PR adds in label-based Dirichlet partitioning. In the Dirichlet sampler that we have, we take an existing dataset and subsample the datapoints according to a Dirichlet distribution with a given $\beta$. In this partitioning example, we take an existing dataset and **split** it into pieces by iterating through the labels and use a Dirichlet distribution to assign a portion of those labels to each client. These two approaches are slightly different and both have been used in literature. 
However, the later is used in two benchmarks ([1](https://arxiv.org/pdf/2206.03655), [2](https://www.computer.org/csdl/journal/oj/2024/01/10316561/1S2UbvQk5Tq)), which, for future experiments, we'd like to reproduce.
Added a test to …
=> Adding in Dirichlet allocation partitioner

fl4health/utils/partitioners.py, tests/utils/partitioners_test.py
[Fix]
This update to the partitioner allows it to retrieve a prior distribution instead of generating a random one.
Updated tests to support extra output.
=> Quick update for partitioner to also get a prior rather than sampling

fl4health/clients/nnunet_client.py, fl4health/feature_alignment/tab_features_preprocessor.py, fl4health/utils/data_generation.py, tests/utils/synthetic_generator_test.py
Feature
Clickup Ticket(s): [Link](https://app.clickup.com/t/8689qhw2n)
This small PR implements synthetic dataset generators based on the original FedProx paper. These generators are to be used in future experiments and replication studies. There are a few small modifications to how the generation takes place, but most of the process is inspired by the original implementation.
**Note**: These synthetic datasets end up with pretty skewed labels, which is a bit disappointing. See the tests for additional illustration. However, they will still be useful. It's just something to be aware of.
Several tests are implemented to check correctness of both generators (IID, non-IID)
=> Adding in synthetic dataset generators based on the original FedProx paper

fl4health/utils/nnunet_utils.py
[Feature | Fix | **Documentation** | Other ]
Short follow up to #268, just adding the documentation that @scarere suggested.
=> Address Shawns CR on previous PR

fl4health/clients/basic_client.py
Clickup Ticket(s): Link(s) if applicable.
I had hardcoded progress bar formatting before. Now it will inherit the same formatting used by FLWR dynamically so that we don't need to track changes made to flower log formatting.
=> modified progress bar formatting to inherit from flwr formatting

fl4health/utils/nnunet_utils.py, tests/utils/nnnunet_utils_test.py
Since the step count of the LR scheduler starts at 1 (imposed by pytorch), the final step will always log that it exceeds the max step count. This PR simply subtracts 1 when calculating the current step to avoid this. 
Update LR scheduler test accordingly.
=> Modify curr step of LR Scheduler to start at 0 instead of 1

fl4health/server/nnunet_server.py
Fixing a slight oversight in the migration the new Reporter Structure. Assertion in load_server_state fails because the typing expects a list instead of type ReportsManager. Only relevant in cases where fault tolerant checkpointing is used.
=> Fix typing on assertion for ReportsManager

fl4health/clients/nnunet_client.py, fl4health/servers/nnunet_server.py, poetry.lock, pyproject.toml
Small PR to add the ability to specify a custom nnunet trainer class.
=> Custom nnunet trainer

fl4health/model_bases/masked_layers/masked_layers_utils.py, tests/models/test_masked_layers.py
Fix
Fixed the bug for converting a model to the masked version by setting the mask scores parameters at the appropriate module level.
Added a new test that uses `load_state_dict`.
=> Converting to masked layers bug fix

.github/workflows/smoke_tests.yaml, fl4health/clients/nnunet_client.py
Clickup Ticket(s): [Add Mixed Precision Training to NnuentClient](https://app.clickup.com/t/868beh5kf)
By default, if you have a CUDA GPU, nnUNetTrainer uses automatic mixed precision training. This casts down the weights and inputs/activation from fp32 to fp16 for certain sets of operations. Weights are kept in fp32 and downcasted. Gradients are compute in fp16 but accumulated in fp32. In order to realize automatic mixed precision training, we must wrap forward pass and loss computation in the autocast context. Additionally, the loss must be scaled to prevent underflow of the gradients which are computed in fp16. This is accomplished via the torch provided GradScaler.
=> Nnunet amp integration

fl4health/checkpointing/checkpointer.py, fl4health/checkpointing/server_module.py, research/picai/single_node_trainer.py, tests/checkpointing/test_per_round_checkpointer.py, tests/smoke_tests/run_smoke_test.py
Fix
When switching off of the default directory "./" for the state checkpointer smoke tests, Andrei uncovered a bug in the way we were checking for the existence of a checkpoint and loading the intermediate state.
Smoke tests now pass without the default directory specified.
=> Smoke test bug fix for Andrei with the state checkpointers

.github/workflows/smoke_tests.yaml, pyproject.toml, tests/smoke_tests/run_smoke_test.py, tests/smoke_tests/test_smoke_tests.py
Fix
**THIS PR BROUGHT THE SMOKE**  💨 💨 💨
This PR addresses an issue with our smoke tests where if one fails (the usual culprit being `test_client_level_dp_breast_cancer`) then it torpedos all of the remaining tests that follow it. Moreover, the error logs of the job looked super scary!
To address this issue, this PR:
1. Ensures that each test explicitly fails if an `Exception` is encountered during the test.
2. Aims to ensure that any lingering cancelled tasks in the event of unexpected test failure (due to Timeout or another reason) are cleared. The reason why we saw the domino effect is because if these cancelled tasks are not cleared, then they will be the next time an event loop starts running. In our case the next test would run the event loop but the hangover cancelled tasks would …
=> Move assert statements out of `run_smoke_test` and into the actual test (for graceful shutdown in case of failure)

examples/nnunet_example/server.py, fl4health/checkpointing/opacus_checkpointer.py, fl4health/checkpointing/server_module.py, fl4health/clients/nnunet_client.py, fl4health/servers/nnunet_server.py
Clickup Ticket(s):
- [Fix nnunet warnings and log spam](https://app.clickup.com/t/868c8gne1)
- [Replace channel properties in local nnunet plans with local fingerprint](https://app.clickup.com/t/868bugrfy)
The nnunet client must modify the global plans and create a local copy. Previously the only fields being updated or checked for edge case errors were the dataset_name, plans_name, data_identifiers and batch_size. This PR improves the local plans file and tailors it more appropriately to the client's local dataset. Changes include
- Updating additional fields containing information about the datasets median image size both before and after resampling
- Updating the foreground_intensity_properties_per_channel. Before we were using stats from the source dataset for normalization and now we …
=> Fix local plans

.github/workflows/publish_and_release.yml
Other
The action we're currently using in our CI/CD to make Github Releases is no longer maintained and also doesn't automatically generate release notes. This PR swaps this action out for another one that is still healthy/maintained and has a feature for generating release notes.
Note and fwiw, this is what we use in `llama-deploy` at LlamaIndex.
N/A
=> [CI/CD] Swap out our gha for Github releases for a better one

CONTRIBUTING.MD, README.md, codecov.yml
Other
Our codecov currently only produces a report, which is useful but probably better to have automatic pass/fail depending on coverage scores (as often the case when using coverage tools). With Codecov, we simply need to include the configuration of such setting within a `codecov.yml` file in our project's root dir.
Other:
- I also updated the "NOTE" [admonitions](https://github.com/orgs/community/discussions/16925) in README.md and CONTRIBUTING.md to look nicer.
Specifically:
N/A
=> [CI/CD] Add `codecov.yml` to add coverage (passing/failing) check

codecov.yml, fl4health/checkpointing/checkpointer.py
Other
Codecov annotations popping up all over the place in our PRs, which are a bit annoying. This PR turns that off by specifying the correct toggle in `codecov.yml`. (Thanks to @emersodb for initial investigations on how to do this.)
In this PR, I temporarily added this `DummyTestClass` without any tests coverage to see if annotations were turned off in the PRs. Happy to report that is the case.
Showing here as well that while the annotations are off, the checks are still in place:
I'll remove this dummy test class after reviewers have given green light on this PR>
N/A
=> [CI/CD] More Codecov configurations

fl4health/clients/nnunet_client.py
Models trained with the nnunet client were significantly slower than identical models trained with the nnunet CLI. After some in depth profiling I identified that the torch.cudnn.benchmark setting, which defaults to False, was being turned on by the CLI to increase model training efficiency by over a factor of 2 at the cost of some overhead time on the first step.
In this PR I added cudnn.benchmark to the nnunet client. I packaged it along with the JIT compiling as they both serve a similar purpose of increasing the efficiency of training steps at the cost of some overhead time on the first step. It seems unlikely that any user would want to use one but not the other, and therefore they are controlled by the same boolean init argument.
I also changed some of the logic to ensure that the …
=> Turn on cudnn.benchmark to accelerate convolutions

poetry.lock, pyproject.toml
The currently pinned version of `ecos==2.0.7.post1` is not available on windows and leads to the pyproject.toml being unresolvable on windows machines. The package was originally pinned for the `qpth` package which already has several unit tests. Changing the requirement to `ecos = ^2.0.1.post1` currently resolves to `ecos==2.0.14` which is available on windows machines. All tests continue to pass so this should not interfere with `qpth`
=> Unrestrict ecos version

.github/workflows/docs_build.yml
Other
Prior to this PR, docs workflow would trigger on pushes to main if certain files (i.e paths) were modified. However, since we have docs now we should just check if all PRs still are able to build docs successfully.
=> [CI/CD] Docs build trigger on all prs to `main`

fl4health/strategies/client_dp_fedavgm.py, tests/smoke_tests/run_smoke_test.py, tests/smoke_tests/test_smoke_tests.py
Fix
The `test_client_level_dp_breast_cancer` smoke test has been flaky for a long time. I was finally able to carve out some time to investigate. It turns out that the flakiness was, indeed, a subtle bug associated with the way we implemented the strategy when we get unlucky with Poisson sampling.
The gist is as follows:
1. The DP mechanism relies on Poisson sampling clients to participate in each round of FL. For the smoke test, we had a Poisson probability of 2/3 with two clients participating. 
2. If, on the **first round**, we got unlucky and sampled no clients for the `fit()` call, we have an optimization in our base server that will skip doing anything, including aggregate fit.
3. However, if we were doing `weighted_aggregation` and `per_client_example_cap` had not been provided, …
=> Fixing an issue with the test_client_level_dp_breast_cancer smoke

tests/clients/test_instance_level.py, tests/clients/test_scaffold_client.py, tests/test_utils/models_for_test.py
Fix
Decoupling some unit tests from examples folder. There shouldn't rely on anything in those folder.
None added. Just migrated to not rely on the examples folder.
=> Decoupling some unit tests from examples folder

.github/workflows/docs_publish.yml
Other
Looks like our permissions were a bit too restrictive for our github pages publish action. The reason why we probably weren't seeing this fail in the last couple of weeks since making the change to permissions is that our docs didn't have anything new to upload. Our action only publishes to the `github_pages` branch if there is something new/different in the docs.
I manually triggered the workflow using cli, and can confirm the workflow now works.
=> [chore] Fix `docs_publish.yml` permmissions

fl4health/mixins/core_protocols.py, fl4health/mixins/personalized/__init__.py, fl4health/mixins/personalized/ditto.py, fl4health/mixins/personalized/utils.py, mypy.ini, poetry.lock, pyproject.toml, tests/mixins/personalized/test_ditto.py, tests/mixins/personalized/test_factory.py, tests/mixins/personalized/test_utils.py, tests/mixins/test_adaptive_drift_constrained.py
Feature
Continuation of using mixins to implement pFL methods. This PR adds the `DittoPersonalizedMixin` which subclasses the previously merged `AdaptiveDriftConstrainedMixin`.
Describe the tests that have been added to ensure the codes correctness, if applicable.
=> [Feature] Add `DittoPersonalizedMixin`

examples/ditto_example/README.md, examples/ditto_example/client.py, examples/ditto_example/client_dynamic.py, examples/ditto_example/config.yaml, examples/ditto_example/server.py, fl4health/mixins/personalized/ditto.py
Documentation
This PR makes use of the recently merged abilities to ditto-ify a `BasicClient` class using our `make_it_personal` class factory function.
- not any unit tests, but did verify that the example works using both commands to launch a client that are now included in the README
=> Add dynamically created version of clients to `examples/ditto_example`

examples/fedbn_example/client.py, fl4health/clients/fedbn_client.py, fl4health/strategies/fedpm.py, poetry.lock, pyproject.toml, tests/clients/test_fedbn_client.py, tests/mixins/personalized/test_ditto.py, tests/mixins/personalized/test_utils.py, tests/mixins/test_adaptive_drift_constrained.py
Feature
Really small PR to add in a sanity check layer for FedBN clients. This allows us to ensure that someone wanting to use BN has a bit of a check on their definition of the parameter exchanger. FedBN really only differs from the Basic Client in a single way (uses a layer exchanger with exclusions), but we weren't really enforcing that anywhere and the example was just "doing so properly" so to speak. This PR just adds in a layer where, if the user wants to use a FedBN client, it checks that they have an exchanger of the correct type.
Test that the enforcement fails if the user does not use the right class for parameter exchange.
=> Creating FedBN client and adding test

examples/nnunet_example/client.py, examples/nnunet_example/server.py, fl4health/checkpointing/client_module.py, fl4health/checkpointing/server_module.py, fl4health/checkpointing/state_checkpointer.py, fl4health/clients/basic_client.py, fl4health/servers/base_server.py, fl4health/utils/early_stopper.py, research/picai/fedavg/client.py, research/picai/fedavg/server.py, research/picai/fl_nnunet/start_client.py, research/picai/fl_nnunet/start_server.py, research/picai/single_node_trainer.py, research/picai/utils.py, tests/checkpointing/test_state_checkpointer.py, tests/servers/test_base_server.py, tests/smoke_tests/load_from_checkpoint_example/client.py, tests/smoke_tests/load_from_checkpoint_example/server.py, tests/utils/test_early_stopper.py
Other
The goal here was just to simplify a few things about the new state checkpointing structure that @fatemetkl is proposing. This includes: 
1. Collapsing a few of the more specific state checkpointing classes into single implementations with defaults that can be overridden
2. Removing the option for in-memory storage. It felt like we had several edge-case type behaviors because of it and I wasn't really sure when one might absolutely need to do that.
3. I also cleaned up a few of the docstrings to be more in the Google docstring style we've been trying to unify on.
Just migrated existing tests to use the new structures and make sure they still passed.
=> Potential way to simplify a few things in refactor.
