examples/apfl_example/server.py
tests/smoke_tests/apfl_config.yaml
tests/smoke_tests/fedprox_config.yaml
tests/smoke_tests/run_smoke_test.py
tests/smoke_tests/scaffold_config.yaml

Other
Clickup Ticket(s): https://app.clickup.com/t/8686m5mqp
- Making smoke tests script more parametrized in order to support other examples
- Adding SCAFFOLD and APFL to smoke tests
The two smoke tests in question.

Add smoke tests for SCAFFOLD, APFL and others, Part 1

---

examples/feature_alignment_example/client.py
fl4health/clients/basic_client.py
fl4health/clients/tabular_data_client.py
fl4health/feature_alignment/constants.py
fl4health/server/tabular_feature_alignment_server.py
tests/clients/test_setup_client_basic.py

[Fix]
Bug fix in `basic_client.py`
Clickup Ticket(s): Link(s) if applicable.
`test_setup_client_basic`

bug fix in basic client

---

research/flamby/fed_heart_disease/evaluate_on_holdout.py
research/flamby/fed_isic2019/evaluate_on_holdout.py
research/flamby/fed_ixi/evaluate_on_holdout.py
research/flamby/fed_ixi/moon/run_fold_experiment.slrm
research/flamby/fed_ixi/perfcl/perfcl_model.py

[Fix]
During evaluating flamby experiments, I have faced a few minor errors and typos. So I fixed them in this small PR.

Flamby experiments

---

fl4health/model_bases/fedper_base.py
tests/models/test_fedper_base.py

Fix
Fixing a bug in the layers_to_exchange function of the FedPer model b…ase class that resulted in no parameters being exchanged with the server. The associated test was passing because the zip still works when one of the lists is empty!
Fixed the test that was failing to properly test the functionality when the list was empty. This zip functionality is very annoying 😂

Fixing a bug in the FedPer layers to exchange function

---

research/flamby/fed_heart_disease/fedper/client.py
research/flamby/fed_heart_disease/perfcl/client.py
research/flamby/fed_ixi/fedper/client.py
research/flamby/fed_ixi/perfcl/client.py
research/flamby/utils.py

[Fix]
Implemented federated checkpointing for additional ablation studies. 
Also addressed a minor issue in the evaluation process, as some federated algorithms do not return tuples like the built-in models like moon_base and fenda_base, which could potentially lead to errors.

Add federated checkpointing

---

examples/warm_up_example/warmed_up_fenda/client.py
fl4health/clients/evaluate_client.py
fl4health/clients/fenda_client.py
fl4health/feature_alignment/tab_features_preprocessor.py
fl4health/losses/mkmmd_loss.py
fl4health/server/base_server.py
tests/losses/test_mkmmd.py

This is a proposed refactor to the mkmmd loss function constructions. There are a lot of tests here and I can definitely improve the documentation. However, I wanted to get it in front of you ASAP.
Note: Most of the other files are miscellaneous stuff that was failing for me in mypy, black, or flake.

Proposed changes to the mkmmd loss function

---

README.md

[Feature | Fix | Documentation | Other ]
Documentation
Clickup Ticket(s): Link(s) if applicable.
Add a short description of what is in this PR.
- Small fix to section heading - "Personalized" instead of "non-Personalized"
Describe the tests that have been added to ensure the codes correctness, if applicable.
NA

Update personalized approaches section header

---

fl4health/clients/moon_client.py
tests/clients/fixtures.py
tests/clients/test_moon_client.py

Fix
Fixing a small bug in the MOON implementation in line with Sana's fix. Adding some tests to ensure the fix is properly functioning.
Some tests to make sure the loss calculations etc. function as expected given the change.

Fixing a small, but significant, bug with MOON.

---

pyproject.toml

[Feature | Fix | Documentation | **Other** ]
Create new release version.
NA

Increment release version

---

examples/ditto_example/client.py
examples/ditto_example/server.py
examples/fedper_example/client.py
examples/fedper_example/server.py
examples/models/fedper_cnn.py
fl4health/clients/basic_client.py
fl4health/clients/moon_client.py
fl4health/model_bases/fedper_base.py

Fixing two small typos

---

README.md

Just updating our README to include the addition of Ditto

Updating the README to include Ditto

---

.github/dependabot.yml

[Feature | Fix | Documentation | Other ]
CI
- Adds a configuration file for dependabot to submit PRs which update github actions (on a weekly basis)
Clickup Ticket(s): Link(s) if applicable.
Add a short description of what is in this PR.
Describe the tests that have been added to ensure the codes correctness, if applicable.

Add dependabot config to update github actions

---

research/picai/prepare_data.py
research/picai/preprocessing.py
research/picai/preprocessing_transforms.py
tests/losses/test_contrastive_loss.py
tests/losses/test_cosine_similarity_loss.py
tests/losses/test_perfcl_loss.py
tests/test_picai/test_preprocess_transforms.py

[Feature | Fix | Documentation | **Other** ]
Clickup Ticket(s): [Add Picai Tranforms Tests](https://app.clickup.com/t/8688q3ah7)
In #155, I added a preprocessing transformation pipeline for PICAI. In this PR, I simply have added tests for those transforms and also fixed a small issue in loss tests from previous PRs when using GPU.
- Tests for PICAI transforms
- Updated Loss tests

Add tests for picai transforms and other test fixes

---

fl4health/utils/dataset.py
fl4health/utils/sampler.py
tests/utils/sampler_test.py

Other
I figured it was a bit easier for me to suggest some changes via a PR for the sampler tests, since there were a few things I thought might be useful to add. Let me know what you think:
1. Creating a synthetic dataset so we don't have to rely on the presence of or downloading the MNIST dataset.
2. Tried to increase the reuse of the dataset so it didn't need to be individually loaded for each test.
3. Added a few small tests for the fixed hash setting to verify everything was sampled in the same exact manner.
Modified some tests to reduce reliance on the MNIST dataset and use a faster to load synthetic dataset that we can reuse.

CIFAR Experiments PR Suggestions

---

fl4health/clients/basic_client.py
fl4health/clients/clipping_client.py
fl4health/clients/ditto_client.py
fl4health/clients/fed_pca_client.py
fl4health/clients/fed_prox_client.py
fl4health/clients/mr_mtl_client.py
fl4health/clients/partial_weight_exchange_client.py
fl4health/clients/scaffold_client.py

Link(s) if applicable: [Fix Client Side Init Bug](https://app.clickup.com/t/8688xdtbd)
Add setup_client call in get_parameters if self.initialized is not true for all clients with get_parameters implementations.

add setup_client call in get_parameters if not initialized

---

README.md
pyproject.toml

Other 
Just a small PR to update the readme a touch and to bump the version number in anticipation of a release.

Updating the README and bump Version Number

---

research/picai/fl_nnunet/nnunet_client.py
research/picai/fl_nnunet/nnunet_utils.py

Was currently bypassing as signal handling [issue](https://github.com/adap/flower/issues/3837) with flwr by temporarily resetting the signal handlers before child processes were spawned by the nnunet client. There was one child subprocess spawned during fingerprint extraction that was accidentally being spawned before the signal handlers were temporarily reset.
Ensured this subprocess was inheriting the default signal handlers. Also improved the implementation by creating a decorator function that would do this so that it doesn't have to be in the main function code. Since the errors were happening stochastically, its hard to conclusively say that this has resolved the issue, but I'm pretty confident this will fix it. We should however continue …

Created reset signal handler decorator

---

fl4health/clients/basic_client.py
tests/clients/test_basic_client.py

Fix
Adding fit end and evaluate end times in the client metrics so FLorist can track it properly.
Fixed existing tests accordingly.

Adding fit end and evaluate end times in the client metrics

---

fl4health/utils/nnunet_utils.py
tests/utils/nnnunet_utils_test.py

Modfiy LR scheduler to have fixed values over defined window size. 
Added test to verify the scheduler anneals the learning rate as expected and produces the appropriate log message when exceed the max_steps it was initialized with.

Modify LR Scheduler + Test

---

fl4health/server/base_server.py

The elapsed time was negative. Minor bugfix

Elapsed time was backwards

---

.github/workflows/static_code_checks.yaml

Fix
Keras vulnerability ignore until there is a fix
NA

Keras vulnerability ignore until there is a fix

---

.gitignore
fl4health/datasets/rxrx1/download.sh

Fix
Just putting in two small edits to the RxRx1 PR. One is just to ignore artifacts generated by the script to the gitignore. The other is to fix a small issue with the script that I encountered
Ran the script on my local to ensure that it downloads everything from scratch

Small download script changes for RxRx1

---

.github/workflows/smoke_tests.yaml
.github/workflows/tests.yaml

Other
This PR add's our standard code coverage tool to the repo, [Codecov](https://app.codecov.io/github/VectorInstitute).
N/A

[chore] Add code coverage to ci/cd

---

tests/utils/metric_test.py
tests/utils/metrics_mangager_test.py

Other
Adding a quick test of the metric manager clear functionality for coverage.
See description.

Testing Metric Manager Clear

---

CITATION.cff
pyproject.toml

Other
Version bump for new release

Bumping version for release

---

fl4health/mixins/core_protocols.py
tests/mixins/test_adaptive_drift_constrained.py
tests/mixins/test_core_protocols.py

Other
As a quick follow-up to the `FlexibleClient` PR, this PR introduces tests for our protocols.
Adds unit tests for protocols to assert methods and annotations exist.

[chore] Add unit tests for protocols

---

CITATION.cff
pyproject.toml

Bumping version to 0.4.0 for release
